#!/bin/bash
#设置备份目标文件夹（Dropbox为例）
Backup=/root/Dropbox/
#日志文件
Log=root/Dropbox/mysql.log
New="$Backup"db$(date +mysql20%y-%m-%d-%H-%M).tgz
Dump="$Backup"db$(date +mysql20%y%m%d%H:%M)
echo "-------------------------------------------" >> $Log
echo $(date +"%y-%m-%d %H:%M:%S") >> $Log
echo "--------------------------" >> $Log
#导出数据库，你需要在my.cnf里设置好user和password
mysqldump --all-databases > $Dump
#压缩
tar czvf $New $Dump >> $Log 2>&1 
echo "[$New]Backup Success!" >> $Log
#删除临时文件
rm $Dump
#启用Dropbox请去掉注释
#/root/.dropbox-dist/dropboxd
